### DISCUSSION TITLE
Custom hashcat binary inside docker

### DISCUSSION THREAD

**Discussion by zyronix** [hashtopolis/server#1038] [Show and tell]
When using the default hashtopolis docker container and you want to use a different hashcat binary (for example you have created an own module) you have to add those binary to the docker container.

Inside the docker container there is the folder 'binaries' which is exposed by apache to the subfolder `/binaries`. Thus `/usr/local/share/hashtopolis/binaries` is accessible via: `http://<docker host ip>/binaries`.

You can either upload the hashcat 7zip to the `/usr/local/share/hashtopolis/binaries` folder inside the container, but note that files stored inside the container are not persistent.

### Persistent storage

1. Create a 7zip file containing the hashcat files
2. Mount the `/usr/local/share/hashtopolis/binaries` inside the container to a folder of the docker host using the docker-compose.yaml file

Add the following line to the docker-compose.yaml: `- /opt/hashtopolis/binaries:/usr/local/share/hashtopolis/binaries:Z`

This will mount `/opt/hashtopolis/binaries` of your host system to `/usr/local/share/hashtopolis/binaries` inside the container.

Also see https://github.com/hashtopolis/server/discussions/1022 for more information, but the content should roughly look like this:

```
...
services:
  hashtopolis-backend:
    container_name: hashtopolis-backend
    image: hashtopolis/backend:latest
    restart: always
    volumes:
      # Where /opt/hashtopolis/<folder> are folders on you host OS.
      - /opt/hashtopolis/binaries:/usr/local/share/hashtopolis/binaries:Z
...
```

3. `docker compose down`
4. `docker compose up`
5. Add a new version to hashcat in the web interface of hashtopolis. Point the url to: `http://<ip of the docker host>/binaries/hashcat-x.x.x.7z

### Temp storage

1. Create a 7zip container a folder `hashcat/`
2. Copy the 7zip inside the docker container: docker cp hashcat-x.x.x.7z hashtopolis-backend:/usr/local/share/hashtopolis/binaries
6. Add a new version to hashcat in the web interface of hashtopolis. Point the url to: `http://<ip of the docker host>/binaries/hashcat-x.x.x.7z`
