### ISSUE TITLE
DevContainer vscode has no permission to create .vscode-server directory

### ISSUE THREAD

**Issue by robinduerhager** [hashtopolis/server#784]
My WSL2 System is broken somehow which is why i have to use the Hyper-V backend for Docker so this could be the issue here. However, with the current `docker-compose.yml` configuration my vscode has no permission to create the `.vscode-server` folder in `/var/www/`:

```log
[2022-06-08T00:20:20.015Z] mkdir: cannot create directory '/var/www/.vscode-server': Permission denied
```

I can however get a container running by using the following addition. I then get a `The terminal process "/usr/sbin/nologin" failed to launch (exit code: 1).` error, however weirdly i can then work in the devcontainer 😅 .
```yml
# hashtopolis service configuration
# ...
ports:
  - "8080:80"
environment: # This is new
  HOME: "/tmp"
# ...
```
